### ISSUE TITLE
/example/simple/index.html 没有防露底

### ISSUE THREAD

**Issue by pimkle** [yuanzm/preventoverscrolljs#7]
我下载了源码, 用一个基础配置的gulp文件把项目跑起来了，用手机微信和手机qq访问了/example/simple/index.html这个文件，发现并没有起到防露底的左右，用chrome dev大概看了下，没有报错，说明文档上的js文件，css样式，也都正常应用上了。是不是我理解有偏差？这么多star不应该啊

**Comment by yuanzm** [comment]
我今天抽时间看一下，这份代码有一年多的时间了，现在运行不起来也是可能的。

**Comment by pimkle** [comment]
今天重新看了下 fixed
